# Generated by Django 5.0.6 on 2024-07-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
